name = "vault-staging"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
DASHBOARD_URL = "https://app-staging.vaultdotenv.io"

routes = [
  { pattern = "api-staging.vaultdotenv.io/*", zone_name = "vaultdotenv.io" }
]

[[d1_databases]]
binding = "DB"
database_name = "vault-db-staging"
database_id = "1e672a32-d1e6-488f-a051-9858f3aeb007"
